name: build lisp kernel
on:
  workflow_dispatch:
  push:
    paths:
      - 'lisp-kernel/**'

jobs:
  compile-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - { dir: linuxx8664 }
          - { dir: linuxx8632 }
    steps:
      - uses: actions/checkout@v3
      - run: cd ${{matrix.dir}}; make

  compile-macos:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: lisp-kernel/darwinx8664
    steps:
      - uses: actions/checkout@v3
      - run: make

  compile-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - { env: mingw64, arch: x86_64, dir: win64 }
          - { env: mingw32, arch: i686, dir: win32 }
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{matrix.env}}
          install: >-
            mingw-w64-${{matrix.arch}}-gcc
            m4
            make
      - uses: actions/checkout@v3
      - run: cd lisp-kernel/${{matrix.dir}}; make
