name: build lisp kernel
on:
  workflow_dispatch:
  push:
    paths:
      - 'lisp-kernel/**'

jobs:
  compile-linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lisp-kernel/linuxx8664
    steps:
      - uses: actions/checkout@v3
      - run: make

  compile-macos:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: lisp-kernel/darwinx8664
    steps:
      - uses: actions/checkout@v3
      - run: make
