name: build lisp kernel
on:
  push:
    paths:
      - 'lisp-kernel/**'

jobs:
  compile-linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lisp-kernel/linux8664
    steps:
      - uses: actions/checkout@v3
      - run: make
